### ISSUE TITLE
RSS-flöde

### ISSUE THREAD

**Issue by l-g** [swedishtechevents/events#12]
Hej

Skulle ni inte kunna lägga till ett RSS-flöde till https://swedishtechevents.com/ ?

Det vore ju strålande!

Tack!

**Comment by frozzare** [comment]
Absolut, en tanke jag själv har haft och något jag började titta på för längesen och glömde bort. Ska ta en titt på de någon dag, finns redan en del kod skriven för det. https://github.com/swedishtechevents/updater/commit/1e0eab7844581f2796a49258ec113fe7abf99bfb

**Comment by frozzare** [comment]
Då finns den en första version av rss flödet uppe https://swedishtechevents.com/rss.xml 👍

**Comment by l-g** [comment]
Efter att ha provat 1,5 vecka...Skulle ni kunna dela upp flödet på län? Det är lite mycket nu...Annars funkar det utmärkt, tack!

**Comment by frozzare** [comment]
Det är inte helt lätt eftersom vi inte sparar historisk data utan uppdaterar allt varje timme och de städerna vi har på https://swedishtechevents.com/ hämtas ut från varje event. 

Det vi skulle kunna göra är att skapa upp separata rss filer för varje stad och uppdatera dom varje timme, får vi inga nya event för någon stad så uppdateras inte den filen utan då ligger dom gamla kvar.

Vad tror du om det?

**Comment by l-g** [comment]
Nu har jag försökt använda det här flödet ett tag och det är "problematiskt", men problemet ligger ju i grund och botten i Swedish Tech Events. Jag antar att syftet med STE är att man ska kunna bläddra och spontanhitta något intressant. Med den premissen kommer här några iakttagelser:

1. RSS-flöder kan ju inte alls fungera för folk utanför Stockholm. Majoriteten av evenemangen är i Stockholm och även folk i Malmö och Göteborg drunknar ju i Stockholms-evenemang.

2. Samtidigt är det ju även för Stockholmare ett överflöd av evenemang pga, trots allt, många evenemang i resten av landet. Just nu listar STE 236 evenemang varav 115 i Stockholm (och få mig inte att börja påpeka att orter som Bromma, Hagalund och Norrmalm finns med i listan...). Ja, ni förstår ju själva.

Jag var lite frånvarande i 1,5 vecka pga semester. När jag kom hem hade jag 210 poster att gå igenom. Det är för mycket. I princip innebär det att man måste ha en rutin för att plöja igenom 10-15 evenemang/dag varav den stora majoriteten är irrelevanta. Träffsäkerheten är för låg.

Frågor/förslag:

1. Län vore väl en lagom indelning? Får väl helt enkelt importera en lista över alla kommuner i landet samt deras länstillhörighet, stadsdelar/postorter i de tre största städerna mm och sedan matcha dem mot resp län.

2. Vet inte om detta ligger hos mig/min RSS-läsare (Feedly) eller i flödet men det vore ju fint om evenemang som redan varit försvann ur flödet.

2.b Om föregående punkt är svår, eller bara för att ni tycker följande är en bra idé: föregå rubriken med startdatum och starttid för evenemanget så kan man snabbt markera saker som lästa som redan gått av stapeln eller om man bara vet att "på tisdag kväll nästa vecka är jag upptagen så jag kan direkt markera alla grejor då som lästa". Då skulle man dessutom kunna sortera listan i bokstavsordning och automatiskt få den i datumordning (om man känner för att vara lite spontan någon dag).

Vilka metadata för resp evenemang har ni tillgång till?

Ytterligare ett sätt filtrera vore ju på kostnaden. Det är ju rätt stor skillnad på saker som kostar 0:-, max 200:- eller flera tusen.

Tekniskt sätt fungerar er lösning utmärkt men den är tyvärr inte särskilt användbar i sitt nuvarande tillstånd. Det är alldeles för mycket som är irrelevant vilket leder till att man inte tar sig tid att kolla vad som erbjuds eftersom det tar för mycket tid. Ni förstår säkert allt det här!

Tack för ert arbete!

**Comment by frozzare** [comment]
Tack för informationen!

Som du själv säger så fungerar inte rss-flödet optimalt och tyvärr är inte de så konstigt då vi inte har jättemycket information att utgå från. 

T ex vi vet inte att Bromma ligger i Stockholm även fast det gör de, vi får nämligen ut Bromma och inte Stockholm om eventet ligger i Bromma. Regioner får vi inte heller ut. 

Detta är datan vi har att spela med
https://swedishtechevents.com/api/events.json

Det vi får ut för meetup och eventbrite skiljer sig också mycket, inte minst på grund av att eventbrite stängt ner sitt sök api. 

På eventbrite får vi inte ut beskrivningarna på event längre (om vi crawlar varje event så skulle vi få det men det gillas nog inte). 

På meetup kanske vi får ut koordinater så där kanske man skulle kunna räkna ut regioner lättare och skapa rss flöden för regioner.

Det hade nog blivit lite konstigt att skapa rss flöden för alla städer vi har i listan idag, t ex alla events i Älvsjö.

Om vi på nått sätt kan få ut en region för en stad så kan vi skapa bättre rss flöden. 

Utan att ha regionen så tror jag dessvärre att detta är de bästa vi kan göra. Vad gäller priset så kan man nog få in det men de löser inte riktigt det stora problem med att inte ha regioner.

Rss flödet uppdateras en gång i timmen så det är alltid färsk data i filen, tror nog feedly och andra tjänster cachar filen och då upplever man problemet med att det är mycket gammal data. All vår data uppdateras en gång i timmen.

**Comment by frozzare** [comment]
Vi skulle kanske använda https://www.papapi.se/ (även fast det inte är aktivt) och börja mappa städer till län (och bygga upp vår egen fil), t ex Bromma till Stockholm. Då blir de bättre på sajten och då kan man nog skapa bättre rss-flöden med.

**Comment by l-g** [comment]
_T ex vi vet inte att Bromma ligger i Stockholm även fast det gör de, vi får nämligen ut Bromma och inte Stockholm om eventet ligger i Bromma. Regioner får vi inte heller ut._

Det är därför jag föreslår att en databastabell med län och alla tänkbara orter, som Älvsjö (stadsdel) och Solna (kommun), länkade till resp län (Stockholm i det här fallet). Den får väl sedan uppdateras om någon besvärligt marknadsmänniska hittar på artificiella namn som "Västermalm".

Vore ju toppen om priset kunde användas som filter.

_Rss flödet uppdateras en gång i timmen_ - men betyder att evenemang som har passerat tas bort?

**Comment by frozzare** [comment]
_Det är därför jag föreslår att en databastabell med län och alla tänkbara orter, som Älvsjö (stadsdel) och Solna (kommun), länkade till resp län (Stockholm i det här fallet). Den får väl sedan uppdateras om någon besvärligt marknadsmänniska hittar på artificiella namn som "Västermalm"._

Ja, nu kom min kommentar lite innan men letade lite och hittade https://www.papapi.se/ som vi kan använda för att börja hitta länen istället för statsdelen. Det löser lite andra konstigheter på sajter.

_Vore ju toppen om priset kunde användas som filter._

I RSS-flödet eller på sajten?

_Rss flödet uppdateras en gång i timmen - men betyder att evenemang som har passerat tas bort?_

Ja, vi hämtar alltid färsk data från de olika tjänsterna vi använder. Vi har ingen egen databas utan skapar bara nya filer utifrån datan vi hämtar.

**Comment by l-g** [comment]
> Vore ju toppen om priset kunde användas som filter.
> 
> I RSS-flödet eller på sajten?

I RSS-flöder. Om man kanske kan skicka in det som en GET-parameter typ ?pricemax=200&län=A etc.

Vad tror du om prefixa rubriken med datum "2020-03-12 17:30 En introduktion till React"?

**Comment by frozzare** [comment]
>I RSS-flöder. Om man kanske kan skicka in det som en GET-parameter typ ?pricemax=200&län=A etc.

GET-parameter blir svårt då vi bara har statiska filer, de som används till sajten är de som ligger i master-branchen här https://github.com/swedishtechevents/swedishtechevents.github.io. 

För de olika länen så får vi skapa flera rss-flöde och lägga upp någonstans på sajten så man kan hitta dom. 

Priset är lite klurigare... att göra något filter är nog inte så lätt utan de man kan göra för varje län rätt enkelt är att ha en gratis och en betald rss-fil. Men jag skulle nog vilja vänta med att införa något sånt tills behovet är större. Ett prisfilter på sajten är nog bättre att börja med isåfall.

>Vad tror du om prefixa rubriken med datum "2020-03-12 17:30 En introduktion till React"?

Absolut, det är nog en bra förbättring för titeln. Använder själv inte RSS-flöden så vet inte riktigt vad som är bäst :)

**Comment by l-g** [comment]
Behöver ju inte vara GET men det är väl bara ett vanligt sätt att göra det på.

Har jag förstått saken rätt om jag tror att ni skannar Eventbrite och Meetup en gång i timmen (eller något sådant) och lägger in i en DB som ni sedan publicerar på www-sidan? Tar ni RSS-flödet direkt från DB:n eller går ni omvägen via www-sidan?

Att lägga till län skulle väl i ett sådant flöde enklast göras genom att preprocessa datat lite innan de sparas i DB:n?

Jag funderar lite på hur man sedan skulle kunna skapa anpassade, individuella, RSS-flöden. Men när jag skriver detta inser jag att det kanske inte behövs för det enda, utöver län, som kan individualiseras är väl priset och län förtjänar "färdiga" flöden i sig själva. Sedan kanske man kunde förbereda några flöden för varje län med pris. Jag föreslår något i stil med

https://swedishtechevents.com/rss.xml
https://swedishtechevents.com/a/rss.xml (Stockholm är ju A-län)
https://swedishtechevents.com/a/200/rss.xml (Max, inkl, 200:-. Föreslår 0, 100, 200. 100 pga kostnaden för en lunch, 200 för att det är belopp många känner att de kan göra av med spontant. Dyrare än så vill man planera saker lite noggrannare.)

Det blir ett hundratal flöden som ska uppdateras en gång i timmen. Känns inte som en orimlig CPU-belastning?

**Comment by frozzare** [comment]
Tack för bra input!

Nu har jag testat och letat efter ett api som fungerar bra. Papapi klarade inte ens av Flemingsberg.. 

Nu får alla event en bättre stad, finns tre regler:
1. Alla event som hämtas via meetup.com får en fördefinierad storstad/område då vi utgår från lat/lng.
2. Det finns nu en fil som mappar vissa städer mot storstad/område. T ex Flemingsberg blir Stockholm.
3. Om man kommer såhär långt så används  https://locationiq.com/ för att försöka hitta en storstad/område. Det blir nog inte rätt alla gånger, det får man nog leva med eftersom vissa statsdelar/områden kan finnas på flera ställen. T ex Bromma finns på flera ställen i Sverige.

Jag valde storstäder/område istället för län eftersom län kan bli så enormt stort i vissa delar av landet och att de flesta eventen finns ändå i storstäder/områden, t ex Göteborg, Malmö, Stockholm, Lund, Umeå osv.

Det skapas rss-filer för dom storstäderna/områden som finns i eventlistan när vi uppdaterar alla events. Det finns inget stöd att ta bort gamla filer (än), så i vissa filer skulle de kunna ligga kvar gammalt innehåll ett tag ifall det inte dyker upp några event där.

Titlar till rss flödet är också uppdaterat enligt "2020-03-12 17:30 En introduktion till React"? samt att de anpassade storstäder/områden får "Swedish Tech Events (Stockholm)" som huvudtitel i rss filen.

Exempel för Stockholm https://swedishtechevents.com/feeds/stockholm.xml

Alla stad specifika feeds finns här
https://github.com/swedishtechevents/swedishtechevents.github.io/tree/master/feeds

Ska fundera på hur man kan presentera det på sajten på nått bra sätt.

-----

Så vår updater funkar är:

1. Varje timme (via cron) anropar vi eventbrite, meetup och github för att hämta event. 
3. Uppdaterar och stänger ärenden i detta repo som är ett event och som har varit.
3. Vi gör om deras data till vår egen data. 
4. Uppdaterar/skapar `/api/events.json` med alla events.
5. Uppdaterar/skapar `/rss.xml` med alla events.
6. Uppdaterar/skapar `/feeds/{city}.xml` med storstad specifika events.

Det enda vi sparar data i är json filer, t ex vi har en config fil med allt vi behöver ha för att kunna köra updatern, t ex tokens, oauth osv. Nu har vi också infört en data-mapp där vi sparar `cities.json` som är en liten mappning av första körningen av att fixa städer. 

Den filen uppdateras av updatern medan den körs, så antal anrop till ett externt api minskar allt eftersom. Den filen uppdateras *inte* på GitHub automatiskt utan det är nått man får göra manuellt. Det är dock en bra fil att ha då svaret från API:t inte alltid behöver stämma, eller om det ens finns och specialfall. 

-----

Priser

Priser vill jag vänta med då jag inte ser att behovet är så stort, rss-flöden kan jag förstå då det faktiskt används rätt mycket men tror inte så många filtrerar på priser faktiskt och är inte jättehög användning av sajten per månad.

Oktober 2019: 109 användare
November 2019: 107 användare
December 2019: 77 användare
Januari 2020: 130 användare

Vet dock inte hur många som använder rss eller inte, men än så länge så vet jag bara om en (dig).

Utifrån dom siffrorna så tror jag att tiden för utvecklingen av rss-filer till priser är större än vad vinsten är, tyvärr.

-----

Jag tror och tycker nog att det blev bättre med lite mer styrda namn på stad än innan, var lite rörigt, speciellt i Stockholm. Hoppas detta blir bättre även för dig. 

Det kommer fortsätta att bli fel på vissa städer, men så får det vara. Det går inte att få de perfekt ifall man inte mappar upp hela Sverige själv eftersom de amerikanska tjänsterna inte alltid har jättebra koll eller det man vill få ut från api:t inte alltid hamnar längst upp och då måste söka fram värdet och då ska man ha något att söka på osv.

**Comment by l-g** [comment]
Strålande! Jag kunde mha av datum och tid direkt avfärda 7 av 9 som dykt upp i Stockholmsflödet när jag la till det.

Nu tror jag RSS-flödet är verkligen användbart och med gott samvete kan marknadsföras! Jag provar några månader och återkommer sedan. Tycker du också borde prova RSS och se hur bra det är!

**Comment by frozzare** [comment]
Grymt! Får prova någon gång, har ett feedly konto med lite bloggar jag borde följa bättre.

**Comment by l-g** [comment]
En kort fråga: hur kommer det sig att det är fler poster i Stockholmsflödet jämfört med hela flödet? Jag markerade båda som helt lästa för 21 timmar sedan, och sedan dess har det dykt upp 29 poster i Stockholm men bara 19 för flödet för hela landet.

**Comment by frozzare** [comment]
Hm, jadu. Svårt att säga om det beror på någon cache någonstans, eller t ex rss-tjänsten gör nått eller så. Det finns också tillfällen där updatern av någon anledning inte kan uppdatera alla filer, t ex strul hos GitHub.

I skrivande stund så ser det ut såhär i flödena (räknat item taggarna, så kan säkert diffa lite mot sajten)

```
Stockholm: 146
Landet: 249
```

Jag tror inte det är något fel på vår sida.

**Comment by l-g** [comment]
Jag gör en ny nollställning och ser vad som händer.

**Comment by l-g** [comment]
Tidsstämpeln för Meetup är en timme fel.

Ämnesraden för https://www.meetup.com/IBM-techtalksandlabs/events/268704285/ är _2020-03-12 **16:00** Audio Classification with Convolutional Neural Networks - IBM TechTalks & labs_ men tiden är 17:00. Förmodar att det är en fråga om tidszoner och enkelt att fixa?

Eventbrite verkar fungera som det ska.

**Comment by frozzare** [comment]
Ja, det verkar som meetup api:t leverar datumet lite fel. Har gjort om lite så finns två varianter av datumet, en som redan är färdig som sträng och kan användas och en som är en timestamp. Deployat ny variant av rss filerna, api:t och sajten så de bör vara rätt överallt nu.
