### ISSUE TITLE
Malmö.rb "What I learned from building a twitter Art Bot"

### ISSUE THREAD

**Issue by olleolleolle** [swedishtechevents/events#4]
Title: Malmö.rb April meetup "What I learned from building a twitter Art Bot"
Description: Malmö.rb is a group of Ruby enthusiasts from sunny Malmö in Sweden.
We meet about monthly to talk about Ruby, programming, and learn from each other. Visit http://malmorb.se/ to know more.  "What I learned from building a twitter Art Bot" Rijksbot, is a twitter bot built with Ruby that responds with images from the Rijksmuseums’ API. This talk covers some of the highs and lows of building it.
City: Malmö
Date: 2018-04-03 17:30:00
Link: http://foocafe.org/malmoe/events/1790-what-i-learned-from-building-a-twitter-art-bot

**Comment by frozzare** [comment]
Thanks! Will be up at 11:00 when the next cron job runs.
