### ISSUE TITLE
Code BEAM STO

### ISSUE THREAD

**Issue by lawrenced** [swedishtechevents/events#7]
Title: Code BEAM STO
Description: 50+ speakers over 2 days, multi-track conference covering Erlang, Elixir and other BEAM languages. It focuses on real-world applications of BEAM languages, concurrency, distributed computing and scalability. It strives to bring together people passionate about the Erlang Ecosystem and high-performance, massively scalable distributed systems.  
City: Stockholm
Date: 2018-05-31 09:00:00
Link: https://www.codesync.global/conferences/code-beam-sto-2018/
Free: false

**Comment by frozzare** [comment]
Updated date since it was wrong and that's why the issue was closed.
